//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jesper/dev/J2ObjcTest/J2ObjcTest/javasrc/HelloWorld.java
//
//  Created by jesper on 22-11-13.
//

#ifndef _HelloWorld_H_
#define _HelloWorld_H_

#import "JreEmulation.h"

@interface HelloWorld : NSObject {
}

- (void)sayHello;
- (id)init;
@end

#endif // _HelloWorld_H_
