//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jesper/dev/J2ObjcTest/J2ObjcTest/javasrc/HelloWorld.java
//
//  Created by jesper on 22-11-13.
//

#include "HelloWorld.h"
#include "java/io/PrintStream.h"
#include "java/lang/System.h"

@implementation HelloWorld

- (void)sayHello {
  NSString *test = @"Dette er en meget lang streng";
  [((JavaIoPrintStream *) nil_chk([JavaLangSystem out])) printlnWithNSString:[test substring:5]];
}

- (id)init {
  return [super init];
}

@end
