//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jesper/dev/J2ObjcTest/J2ObjcTest/javasrc/AbstractConnection.java
//
//  Created by jesper on 26-11-13.
//

#include "AbstractConnection.h"
#include "JSONObject.h"

@implementation AbstractConnection

- (JSONObject *)doGetWithNSString:(NSString *)url {
    NSURLRequest *request = [NSURLRequest requestWithURL:[NSURL URLWithString:url]];
    NSData *response = [NSURLConnection sendSynchronousRequest:request returningResponse:nil error:nil];
    NSString *jsonString = [[NSString alloc] initWithData:response encoding:NSUTF8StringEncoding];
    JSONObject *jsonObject = [[JSONObject alloc] initWithNSString:jsonString];
    return jsonObject;
}

- (JSONObject *)doPostWithNSString:(NSString *)url
                      withNSString:(NSString *)body {
    return nil;
}

- (id)init {
  return [super init];
}

- (void)copyAllFieldsTo:(AbstractConnection *)other {
  [super copyAllFieldsTo:other];
}

@end
